name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: build/libs/*-all.jar
