name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*'
  workflow_call:
    inputs:
      version:
        type: string

jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - id: version
        name: Detect version
        run: echo "version=${VERSION:-0.0+git-${GITHUB_SHA::7}}" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ inputs.version }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pversion=${{ steps.version.outputs.version }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: build/libs/*-all.jar
