name: GitHub release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  version:
    name: Extract version from git
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        name: Extract version
        run: |
          TAG=${{ github.ref }}
          VERSION=${TAG#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  build:
    name: Build
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
  release:
    name: Prepare release
    needs:
      - version
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gradle-build
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.version.outputs.version }}
          generate_release_notes: true
          draft: true
          files: '*'